/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <SpeedUpLevelComm.h>

int32_t SpeedUpLevelCommConverter::fromString(const std::string& input)
{
    if (input=="NO_SPEEDUP_COMM") {
        return static_cast<int32_t>(NO_SPEEDUP_COMM);
    }
    if (input=="MED_SPEEDUP_COMM") {
        return static_cast<int32_t>(MED_SPEEDUP_COMM);
    }
    if (input=="HIGH_SPEEDUP_COMM") {
        return static_cast<int32_t>(HIGH_SPEEDUP_COMM);
    }
    return -1;
}

std::string SpeedUpLevelCommConverter::toString(int32_t input)
{
    switch(static_cast<SpeedUpLevelComm>(input)) {
    case NO_SPEEDUP_COMM:
        return "NO_SPEEDUP_COMM";
    case MED_SPEEDUP_COMM:
        return "MED_SPEEDUP_COMM";
    case HIGH_SPEEDUP_COMM:
        return "HIGH_SPEEDUP_COMM";
    }
    return "";
}
